/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentmanagementfront;

/**
 *
 * @author zhuan
 */
public class CouseListJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CouseListJPanel
     */
    public CouseListJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPaneCourseList = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        courseJPanel1 = new studentmanagementfront.CourseJPanel();

        jScrollPaneCourseList.setViewportView(jList1);

        jSplitPane1.setLeftComponent(jScrollPaneCourseList);
        jSplitPane1.setRightComponent(courseJPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private studentmanagementfront.CourseJPanel courseJPanel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPaneCourseList;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
