/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentmanagementfront;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import studentmanagementbackend.Database;
import studentmanagementbackend.Exam;
import studentmanagementbackend.Student;
import studentmanagementbackend.ExamReport;

/**
 *
 * @author zhuan
 */
public class ExamReportListJPanel extends ContentJPanel {

    /**
     * Creates new form ExamReportJPanel
     */
    public ExamReportListJPanel() {
        initComponents();
        ArrayList<Exam> exams=Database.getAllExams();
        DefaultListModel modelExams=new DefaultListModel();
        modelExams.addAll(exams);
        this.jListExam.setModel(modelExams);
        ArrayList<Student> students=Database.getAllStudents();
        DefaultListModel modelStudents=new DefaultListModel();
        modelStudents.addAll(students);
        this.jListStudents.setModel(modelStudents);
        this.examReportJPanel1.setState(PanelState.Initial);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jSplitPane2 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListExam = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListStudents = new javax.swing.JList<>();
        examReportJPanel1 = new studentmanagementfront.ExamReportJPanel();

        jListExam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListExamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListExam);

        jSplitPane2.setLeftComponent(jScrollPane1);

        jListStudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListStudentsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jListStudents);

        jSplitPane2.setRightComponent(jScrollPane2);

        jSplitPane1.setLeftComponent(jSplitPane2);
        jSplitPane1.setRightComponent(examReportJPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jListExamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListExamMouseClicked
        // TODO add your handling code here:
        onSelect();
    }//GEN-LAST:event_jListExamMouseClicked

    private void jListStudentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListStudentsMouseClicked

        // TODO add your handling code here:
        onSelect();
    }//GEN-LAST:event_jListStudentsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private studentmanagementfront.ExamReportJPanel examReportJPanel1;
    private javax.swing.JList<String> jListExam;
    private javax.swing.JList<String> jListStudents;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    // End of variables declaration//GEN-END:variables

    

    private void onSelect() {
        int idxExam=this.jListExam.getSelectedIndex();
        if (idxExam<0) {
            this.examReportJPanel1.setState(PanelState.Initial);
            return;
        }
        int idxStudent=this.jListStudents.getSelectedIndex();
        if (idxStudent<0) {
            this.examReportJPanel1.setState(PanelState.Initial);
            this.examReportJPanel1.clearAll();
            return;
        }
        Exam exam=(Exam)((DefaultListModel)this.jListExam.getModel()).get(idxExam);
        Student student=(Student)((DefaultListModel)this.jListExam.getModel()).get(idxStudent);
        String examReportId=student.getId()+"@"+exam.getId();
        ExamReport report=Database.findExamReport(examReportId);
        if (report==null) {
            report=new ExamReport();
            report.setId(null);
            report.setExam(exam);
            report.setStudent(student);
            report.setScore(0);
            report.setDate(new Date());
        }
        this.examReportJPanel1.setData(report);
        this.examReportJPanel1.setState(PanelState.InUpdate);
    }
}
