/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentmanagementfront;

import java.awt.CardLayout;
import java.awt.Container;

/**
 *
 * @author zhuan
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studentListJPanel1 = new studentmanagementfront.StudentListJPanel();
        couseListJPanel1 = new studentmanagementfront.CouseListJPanel();
        examListJPanel1 = new studentmanagementfront.ExamListJPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuStudent = new javax.swing.JMenu();
        jMenuItemManageStudents = new javax.swing.JMenuItem();
        jMenuCourse = new javax.swing.JMenu();
        jMenuItemManageCourses = new javax.swing.JMenuItem();
        jMenuExam = new javax.swing.JMenu();
        jMenuItemManageExams = new javax.swing.JMenuItem();
        jMenuReport = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        studentListJPanel1.setName("Student"); // NOI18N
        getContentPane().add(studentListJPanel1, "Student");

        couseListJPanel1.setName("Course"); // NOI18N
        getContentPane().add(couseListJPanel1, "Course");

        examListJPanel1.setName("Exam"); // NOI18N
        getContentPane().add(examListJPanel1, "Exam");

        jMenuStudent.setText("Student");

        jMenuItemManageStudents.setText("Manage Students");
        jMenuItemManageStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemManageStudentsActionPerformed(evt);
            }
        });
        jMenuStudent.add(jMenuItemManageStudents);

        jMenuBar1.add(jMenuStudent);

        jMenuCourse.setText("Course");

        jMenuItemManageCourses.setText("Manage Courses");
        jMenuItemManageCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemManageCoursesActionPerformed(evt);
            }
        });
        jMenuCourse.add(jMenuItemManageCourses);

        jMenuBar1.add(jMenuCourse);

        jMenuExam.setText("Exam");

        jMenuItemManageExams.setText("Manage Exams");
        jMenuItemManageExams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemManageExamsActionPerformed(evt);
            }
        });
        jMenuExam.add(jMenuItemManageExams);

        jMenuBar1.add(jMenuExam);

        jMenuReport.setText("Report");
        jMenuBar1.add(jMenuReport);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemManageStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemManageStudentsActionPerformed
        // TODO add your handling code here:
        Container contentPane=this.getContentPane();
        ((CardLayout)contentPane.getLayout()).show(contentPane, "Student");
    }//GEN-LAST:event_jMenuItemManageStudentsActionPerformed

    private void jMenuItemManageCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemManageCoursesActionPerformed
        // TODO add your handling code here:
        Container contentPane=this.getContentPane();
        ((CardLayout)contentPane.getLayout()).show(contentPane, "Course");
    }//GEN-LAST:event_jMenuItemManageCoursesActionPerformed

    private void jMenuItemManageExamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemManageExamsActionPerformed
        // TODO add your handling code here:
        Container contentPane=this.getContentPane();
        ((CardLayout)contentPane.getLayout()).show(contentPane, "Exam");
    }//GEN-LAST:event_jMenuItemManageExamsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private studentmanagementfront.CouseListJPanel couseListJPanel1;
    private studentmanagementfront.ExamListJPanel examListJPanel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCourse;
    private javax.swing.JMenu jMenuExam;
    private javax.swing.JMenuItem jMenuItemManageCourses;
    private javax.swing.JMenuItem jMenuItemManageExams;
    private javax.swing.JMenuItem jMenuItemManageStudents;
    private javax.swing.JMenu jMenuReport;
    private javax.swing.JMenu jMenuStudent;
    private studentmanagementfront.StudentListJPanel studentListJPanel1;
    // End of variables declaration//GEN-END:variables
}
