/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentmanagementfront;

import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author zhuan
 */
public class StudentListJPanel extends javax.swing.JPanel {

    /**
     * Creates new form StudentListJPanel
     */
    public StudentListJPanel() {
        initComponents();
        loadStudents();
        setInitialState();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        studentJPanel1 = new studentmanagementfront.StudentJPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListStudents = new javax.swing.JList<>();

        jSplitPane1.setRightComponent(studentJPanel1);

        jScrollPane1.setViewportView(jListStudents);

        jSplitPane1.setLeftComponent(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> jListStudents;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private studentmanagementfront.StudentJPanel studentJPanel1;
    // End of variables declaration//GEN-END:variables

    private ArrayList<Student> students=new ArrayList();
    private void loadStudents() {
        this.students=Database.loadStudents();
        DefaultListModel listModel=new DefaultListModel(this.students);
        this.jListStudents.setModel(listModel);
    }

    private void setInitialState() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
